"""k-safeguard public API."""

from .chosung import (
    CHOSUNG_CANDIDATE_VERSION,
    ChosungCandidate,
    ChosungCandidateResult,
    ChosungLexicon,
    ChosungReplacement,
    LexiconPartialMatch,
    chosung_signature,
    expand_korean_noun_particles,
    generate_chosung_candidates,
)
from .gateway import (
    DEFAULT_MAX_VIEWS,
    CandidateProposal,
    CandidateProvider,
    Gateway,
    GatewayResult,
    TextView,
)
from .execution import (
    AsyncBatchGuardrailClassifier,
    AsyncGuardrailClassifier,
    BatchClassifierOutput,
    BatchClassifierOutputError,
    BatchGuardrailClassifier,
    ClassifierCallTrace,
    ClassifierErrorMode,
    ClassifierExecutionError,
    ClassifierOutput,
    ClassifierResult,
    GatewayEvaluation,
    GuardrailClassifier,
    ViewEvaluation,
    evaluate_gateway,
    evaluate_gateway_async,
    evaluate_gateway_batch,
    evaluate_gateway_batch_async,
)
from .normalization import (
    NORMALIZER_VERSION,
    NormalizationEdit,
    NormalizationResult,
    normalize_korean,
)


__version__ = "0.2.0"

__all__ = [
    "CHOSUNG_CANDIDATE_VERSION",
    "DEFAULT_MAX_VIEWS",
    "NORMALIZER_VERSION",
    "CandidateProposal",
    "CandidateProvider",
    "AsyncBatchGuardrailClassifier",
    "AsyncGuardrailClassifier",
    "BatchClassifierOutput",
    "BatchClassifierOutputError",
    "BatchGuardrailClassifier",
    "ClassifierCallTrace",
    "ClassifierErrorMode",
    "ClassifierExecutionError",
    "ClassifierOutput",
    "ClassifierResult",
    "ChosungCandidate",
    "ChosungCandidateResult",
    "ChosungLexicon",
    "ChosungReplacement",
    "Gateway",
    "GatewayEvaluation",
    "GatewayResult",
    "LexiconPartialMatch",
    "NormalizationEdit",
    "NormalizationResult",
    "TextView",
    "GuardrailClassifier",
    "ViewEvaluation",
    "__version__",
    "chosung_signature",
    "expand_korean_noun_particles",
    "evaluate_gateway",
    "evaluate_gateway_async",
    "evaluate_gateway_batch",
    "evaluate_gateway_batch_async",
    "generate_chosung_candidates",
    "normalize_korean",
]
